[feature] ActivityCard component
babelsh/mission-us-frontend pull request #11
Opened 2018-09-20 01:49 UTC by rartner

* Creating ActivityCard component
* Listing activities on Home using grid-list
* Corrections and new unit tests

## Pics
`Home screen:`
![image](https://user-images.githubusercontent.com/21064354/45790987-f6005f00-bc5d-11e8-8812-d0d67b6db2a8.png)

## TESTS
* Added unit tests for comparing snapshots
* Correcting unit tests for using `Vuetify`
* Changing scripts for running and updating unit tests (see README)

2018-09-20 10:34 UTC, mathvalenza requested changes

2018-09-20 10:34 UTC, mathvalenza commented on src/components/ActivityCard.vue
> +      ></v-img>
We could close v-img with "/>". Maybe it fits into one line

2018-09-20 10:34 UTC, mathvalenza commented on src/components/ActivityCard.vue
> +          {{ finalized ? 'Finalizada' : 'Feito' }}
We shouldn't use any logic in the template section, so we can use a computed property called "buttonLabel", for example. By the way, what is the difference between "Finalizada" and "Feito" and what is the link with the boolean finalized

2018-09-20 10:34 UTC, mathvalenza commented on src/views/Home.vue
> +          ></activity-card>
/>

2018-09-20 10:34 UTC, mathvalenza commented on src/components/ActivityCard.vue
> +      return '';
Using this, maybe we don't need a default case and the console.log could stay here OR we could return ' ' inside the code block in default case

2018-09-20 10:34 UTC, mathvalenza commented on src/components/ActivityCard.vue
> +      required: true,
In the future, rendering this component will depends on a Promise. We can keep this but the parent component should have and "v-if" condition. Anyway, it is just a comment

2018-09-20 23:41 UTC, rartner commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Card de Atividade (3)](https://trello.com/c/39EDjvED/62-feature-card-de-atividade-3)

2018-09-21 10:23 UTC, mathvalenza approved these changes

2018-09-21 17:20 UTC, cuzik approved these changes
:cow:

2018-09-21 17:58 UTC, merged