Trail
babelsh/mission-us-frontend pull request #5
Opened 2018-09-17 18:51 UTC by mathvalenza

This is the first version of the Trail component, that shows the title, an image and a abstract of the trail

2018-09-17 19:40 UTC, rartner commented on src/views/Trail.vue
> +<div>
missing indent?

2018-09-17 19:40 UTC, rartner commented on src/views/Trail.vue
> +
has no content. couldn't be removed?

2018-09-17 20:14 UTC, cuzik requested changes
Can we write test for these components?

Resolve the conflicts.

2018-09-17 20:14 UTC, cuzik commented on src/views/Trail.vue
> +</style>
Missing extra line on the end.

2018-09-17 20:14 UTC, cuzik commented on src/views/Home.vue
> +};
Remove `;`

2018-09-17 20:14 UTC, cuzik commented on src/views/Home.vue
> +import Trail from './Trail';
Remove ;

2018-09-17 20:17 UTC, cuzik commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Criar component para o card de Trilha (3)](https://trello.com/c/8PhZcoMp/63-feature-criar-component-para-o-card-de-trilha-3)

2018-09-18 10:12 UTC, rartner commented on tests/unit/Home.spec.js
> +import Home from '../../src/views/Home.vue';
`@/views/Home.vue` should work here

2018-09-18 10:12 UTC, rartner commented on tests/unit/Login.spec.js
> +import Login from '../../src/views/Login.vue';
`@/views/Login.vue` should work here

2018-09-18 10:12 UTC, rartner commented on tests/unit/Trail.spec.js
> +import Trail from '../../src/views/Trail.vue';
`@/views/Trail.vue` should work here

2018-09-18 10:12 UTC, rartner commented on tests/unit/Trail.spec.js
> +import Trail from '../../src/views/Trail.vue';
I think `Trail` is a `component`, not a `view`

2018-09-18 10:51 UTC, rartner approved these changes

2018-09-18 14:23 UTC, cuzik approved these changes
:cow:

2018-09-18 14:31 UTC, merged